# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: All Of Tech
author: Ankur Singh
description: >- # this means to ignore newlines until "baseurl:"
  My journey into blogging
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alloftech.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username: alloftech

show_excerpts: true
permalink: /:collection/:year-:month-:day-:title:output_ext

staticman_url: "https://blog-commenting.herokuapp.com/v3/entry/github/alloftech/alloftech.github.io/main/comments"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-sitemap

include:
  - _extras

reCaptcha:
    enabled: true
    siteKey: "6LeCNu4hAAAAABntTU83a6eTY9nxpwByKKMEsvjG"
    secret: "Uda5LR6c8+lk25zXxHLcae3FtEMnnqUiBMiq5VJu8tjMixMwoc+9qqdgr6j4p8GnsTvrFVgKdPItHFbwSifVp6+eHqsKy1FizrAPF2pgQITuH7vekzUUaKYRT/NkRh8u23gnA9U+ki4C+Rx9m9/YPeZNHsupMm0giMWqItQYcQ24Xq9uxDsTPSN4h5bJqFop40pxGpQz4p7AximF3/yRm9fQsDeZ682C9Gxdcbn80tmg/TFJQJpdLLV8CAKwvXzTdgJymATm4KMMSWoMbZdxZXu+y6bdi15DtJ8/OvMa2X/ydEv0akqPshwF/c0OAAyo8TVoJuIbVf5sNQAMUUIzDg=="
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
